name: Lab 3 - Kubernetes (KinD)

on: [push]

env:
  APP_NAME: ecommerce-app

jobs:
  k8s-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lower case owner name
        run: echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Create KinD cluster
        uses: helm/kind-action@v1.12.0
        with:
          cluster_name: kind

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.OWNER_LC }}/${{ env.APP_NAME }}:latest ./back

      - name: Load image into KinD
        run: |
          kind load docker-image ghcr.io/${{ env.OWNER_LC }}/${{ env.APP_NAME }}:latest --name kind

      - name: Prepare Secret
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: |
          envsubst < k8s/secret.yaml > k8s/secret_ready.yaml
          mv k8s/secret_ready.yaml k8s/secret.yaml

      - name: Pull and Load Postgres image
        run: |
          docker pull postgres:15-alpine
          kind load docker-image postgres:15-alpine --name kind

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/

      - name: Debug Postgres Status
        if: always()
        run: |
          kubectl get pods
          kubectl describe pod -l app=postgres
          kubectl logs -l app=postgres

      - name: Wait for Database
        run: |
          kubectl rollout status deployment/postgres-deployment --timeout=60s

      - name: Wait for backend to be ready
        run: |
          kubectl rollout status deployment/backend-deployment --timeout=90s

      - name: Run Master Validation Script
        run: |
          chmod +x ./tests/lab3_test.sh
          ./tests/lab3_test.sh